### PR TITLE
change to new production modulepath

### PR DESCRIPTION
**Pull request by kjhenner**

### CODE REVIEW

**Comment by casharma** [comment]
Is it possible that someone might try to use this on an older VM we've published?

**Comment by kjhenner** [comment]
For now, our priority is making the Learning VM work with PE 2015.2. If we want to support older Puppet versions, that's going to be a much broader project and conversation.

**Comment by casharma** [comment]
I understand that part. My question was - with how things are set up, would someone with an existing VM, downloaded and in use, have to use the updated learning module by installing it from the Forge, for example?

**Comment by joshsamuelson** [comment]
This module is not on the forge.  It's only used during the VM build and we clean up the repo so students would not be running this themselves.

**Pull request merged**
